linters:
  IdSelector:
    enabled: false
  QualifyingElement:
    enabled: false
  VendorPrefix:
    enabled: false
  DuplicateProperty:
    enabled: false
  ImportantRule:
    enabled: false
  SelectorDepth:
    enabled: false